version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Oder eine andere passende Node.js-Version
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

artifacts:
  files:
    - build/**  # Speichert den gebauten Output-Ordner
  base-directory: build  # Setzt den `build/`-Ordner als Wurzel für die Artefakte