version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci  # Faster and more reliable for CI/CD

  build:
    commands:
      - echo "Building the React app..."
      - npm run build  # Ensure your app builds into the `dist` folder

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'  # Includes all files inside the `dist/` directory
  base-directory: dist